import { Dimensions, StyleSheet } from "react-native";
import { themes } from "../../global/themes";

export const style = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: themes.white,
        marginTop: 50,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    greeting: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#000000",
    },
    points: {
        fontSize: 12,
        color: "gray",
    },
    profileImage: {
        width: 50,
        height: 50,
        borderRadius: 20,
        backgroundColor: themes.secundary,
    },
    dailyRoutine: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f2f2f2",
        borderRadius: 10,
        padding: 10,
        borderWidth: 1,
        borderColor: "#ccc",
        justifyContent: "space-between",
        marginVertical: 20,
    },
    iconContainer: {
        backgroundColor: "#ffffff",
        padding: 10,
        borderRadius: 10,
    },
    icon: {
        width: 20,
        height: 20,
    },
    textContainer: {
        flex: 1,
        marginLeft: 10,
    },
    dailyText: {
        fontSize: 16,
        fontWeight: "500",
        color: "#333",
    },
    progressWrapper: {
        alignItems: "center",
        backgroundColor: '#ffffff',
        padding: 5,
        borderRadius: 10,
    },
    progressPercentage: {
        fontSize: 12,
        color: "black",
        marginBottom: 4,
    },
    progressContainer: {
        backgroundColor: "#e0e0e0",
        borderRadius: 5,
        height: 8,
        width: 50,
        justifyContent: "center",
    },
    progressBar: {
        width: "70%", 
        height: "100%",
        backgroundColor: "#bda77b",
        borderRadius: 5,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 10,
        backgroundColor: "white",
    },
    recommendations: {
        flexDirection: "row",
        height: 140,
    },
    recommendationsProducts: {
        flexDirection: "row",
        height: 150,
        width: "100%",
    },
    card: {
        width: Dimensions.get("window").width * 0.42,
        height: 230,
        borderRadius: 15,
        overflow: "hidden",
        backgroundColor: "#ffffff",
        position: "relative",
        marginVertical: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    cardProducts: {
        width: Dimensions.get("window").width * 0.30,
        height: 160,
        borderRadius: 15,
        overflow: "hidden",        
        color: "#000",
        backgroundColor: "000",
        position: "relative",
        marginVertical: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    cardImage: {
        width: "100%",
        height: "100%",
        borderRadius: 15,
    },
    timeContainer: {
        position: "absolute",
        top: 5,
        left: 5,
        width: 45,
        borderRadius: 5,
        backgroundColor: "rgba(250, 235, 215, 0.4)",
        flexDirection: "row",
        paddingVertical: 1,
        paddingHorizontal: 2,
        justifyContent: "center",
        alignItems: "center",
        margin: 5,
    },
    timeContainerWrapper: {
        flexDirection: "row",
        alignItems: "center",
        opacity: 1,
    },
    timeText: {
        fontSize: 12,
        color: "#000",
        padding: 1,
    },
    playButtonContainer: {
        position: "absolute",
        top: 10,
        right: 10,
        backgroundColor: "white",
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        opacity: 0.9,
    },
    playIcon: {
        width: 15,
        height: 15,
    },
    cardTextContainer: {
        position: "absolute",
        bottom: 10,
        left: 10,
        right: 10,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        borderRadius: 10,
    },
    outText: {
        padding: 5,
        fontSize: 14,
        color: "#000",
        textAlign: "center",
    },
    colProducts: {
        flexDirection: "row",
        width: "100%",
        height: 50,
    },
    cardText: {
        padding: 5,
        fontSize: 14,
        color: "#000",
        textAlign: "center",
    },
    navbar: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: 60,
        backgroundColor: "#faedde",
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 10,
    },
    navbarIcon: {
        width: 24,
        height: 24,
    },
    iconBox: {
        width: "20%",
        height: "100%",
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#faedde",
    },
    centerIcon: {
        width: "20%",
        height: 70,
        position: 'relative',
        bottom: 15,
        backgroundColor: themes.tertiary,
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        // Optional: Add elevation/shadow
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
});
